basePath: /
externalDocs:
  description: OpenAPI
host: localhost:8080
info:
  contact: {}
  description: This is a order service API.
  title: Order Service API
  version: "1.0"
paths: {}
swagger: "2.0"
